"use client"

import { FormEvent, useEffect, useMemo, useState } from "react"

type Relationship={id:string;type:"PARENT"|"CHILD"|"SPOUSE";fromId:string;toId:string}
type Person={id:string;firstName:string;lastName:string;gender:string|null;birthYear:number|null;deathYear:number|null;birthPlace:string|null;biography:string|null;relationships:Relationship[];relatedTo:Relationship[]}

const initials=(p:Person)=>`${p.firstName[0]||""}${p.lastName[0]||""}`.toUpperCase()

export default function Home(){
 const [people,setPeople]=useState<Person[]>([])
 const [selected,setSelected]=useState<string>("")
 const [tab,setTab]=useState("tree")
 const [query,setQuery]=useState("")
 const [modal,setModal]=useState<"add"|"edit"|"relationship"|null>(null)
 const [loading,setLoading]=useState(true)
 const [error,setError]=useState("")

 async function loadPeople(){
  try{setLoading(true);const r=await fetch("/api/people",{cache:"no-store"});if(!r.ok)throw new Error("Could not load family data");const data=await r.json();setPeople(data);setSelected(s=>data.some((p:Person)=>p.id===s)?s:(data[0]?.id||""));setError("")}catch(e){setError(e instanceof Error?e.message:"Database connection failed")}finally{setLoading(false)}
 }
 useEffect(()=>{loadPeople()},[])
 const current=people.find(p=>p.id===selected)||people[0]
 const parents=useMemo(()=>current?people.filter(p=>current.relatedTo.some(r=>r.type==="PARENT"&&r.fromId===p.id)||current.relationships.some(r=>r.type==="CHILD"&&r.toId===p.id)):[],[people,current])
 const children=useMemo(()=>current?people.filter(p=>current.relationships.some(r=>r.type==="PARENT"&&r.toId===p.id)||current.relatedTo.some(r=>r.type==="CHILD"&&r.fromId===p.id)):[],[people,current])
 const spouse=useMemo(()=>{if(!current)return undefined;const r=[...current.relationships,...current.relatedTo].find(x=>x.type==="SPOUSE");return r?people.find(p=>p.id===(r.fromId===current.id?r.toId:r.fromId)):undefined},[people,current])
 const filtered=people.filter(p=>`${p.firstName} ${p.lastName}`.toLowerCase().includes(query.toLowerCase()))

 async function addPerson(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={firstName:String(f.get("firstName")),lastName:String(f.get("lastName")),gender:String(f.get("gender")),birthYear:f.get("birthYear")||null,deathYear:f.get("deathYear")||null,birthPlace:String(f.get("birthPlace")||""),biography:String(f.get("biography")||"")};const r=await fetch("/api/people",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError("Could not add person");return}const p=await r.json();setModal(null);await loadPeople();setSelected(p.id);setTab("profile")}
 async function editPerson(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!current)return;const f=new FormData(e.currentTarget);const body={id:current.id,firstName:String(f.get("firstName")),lastName:String(f.get("lastName")),gender:String(f.get("gender")),birthYear:f.get("birthYear")||null,deathYear:f.get("deathYear")||null,birthPlace:String(f.get("birthPlace")||""),biography:String(f.get("biography")||"")};const r=await fetch("/api/people",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){setError("Could not save changes");return}setModal(null);await loadPeople()}
 async function relation(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!current)return;const f=new FormData(e.currentTarget);const type=String(f.get("type")) as Relationship["type"];const other=String(f.get("person"));const r=await fetch("/api/relationships",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fromId:current.id,toId:other,type})});if(!r.ok){const d=await r.json().catch(()=>({}));setError(d.error||"Could not create relationship");return}setModal(null);await loadPeople()}
 async function remove(){if(!current||!confirm(`Delete ${current.firstName} ${current.lastName}?`))return;const r=await fetch("/api/people",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:current.id})});if(!r.ok){setError("Could not delete person");return}await loadPeople()}

 const Card=({p}:{p:Person})=><button className={`person ${selected===p.id?"selected":""}`} onClick={()=>setSelected(p.id)}><div className="personrow"><div className="avatar">{initials(p)}</div><div><h3>{p.firstName} {p.lastName}</h3><small>{p.birthYear||"Unknown"}{p.deathYear?` — ${p.deathYear}`:""}</small></div></div></button>
 if(loading)return <div className="app"><main className="content"><h1>Loading family tree…</h1></main></div>
 return <div className="app"><header className="topbar"><div className="brand"><div className="logo">⌘</div><span>Family Tree</span></div><div className="actions"><button className="secondary" onClick={()=>setModal("relationship")} disabled={!current}>Connect</button><button className="primary" onClick={()=>setModal("add")}>+ Add person</button></div></header>
 <div className="layout"><aside className="sidebar"><nav className="nav">{[["tree","🌳 Tree"],["people","👥 People"],["profile","👤 Profile"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav><div style={{marginTop:28,padding:14}}><small className="muted">Your family</small><div style={{fontWeight:800,marginTop:6}}>{people.length} people</div><div className="muted" style={{fontSize:12,marginTop:4}}>Saved in PostgreSQL</div></div></aside>
 <main className="content">{error&&<div className="card" style={{marginBottom:16,color:"#b42318"}}>{error}</div>}
 {tab==="tree"&&<><div className="heading"><div><h1>Family tree</h1><p className="muted">Click a person to explore parents, spouse and children.</p></div></div><div className="grid" style={{marginBottom:16}}><div className="card stat"><div><span>People</span><strong>{people.length}</strong></div><span>members</span></div><div className="card stat"><div><span>Connected</span><strong>{people.filter(p=>p.relationships.length||p.relatedTo.length).length}</strong></div><span>members</span></div><div className="card stat"><div><span>Relationships</span><strong>{Math.floor(people.reduce((n,p)=>n+p.relationships.length,0))}</strong></div><span>links</span></div></div>{current?<div className="tree"><div className="generation">{parents.map(p=><Card key={p.id} p={p}/>)}</div>{parents.length>0&&<div className="connector"/>}<div className="generation"><Card p={current}/>{spouse&&<Card p={spouse}/>}</div>{children.length>0&&<><div className="connector"/><div className="generation">{children.map(p=><Card key={p.id} p={p}/>)}</div></>}</div>:<div className="card empty">No family members yet. Add the first person to begin.</div>}</>}
 {tab==="people"&&<><div className="heading"><div><h1>People</h1><p className="muted">Manage everyone stored in your family database.</p></div><button className="primary" onClick={()=>setModal("add")}>+ Add person</button></div><div className="card"><input className="search" placeholder="Search by name..." value={query} onChange={e=>setQuery(e.target.value)}/><table className="table"><thead><tr><th>Name</th><th>Birth</th><th>Location</th><th>Relationships</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} onClick={()=>{setSelected(p.id);setTab("profile")}} style={{cursor:"pointer"}}><td><b>{p.firstName} {p.lastName}</b></td><td>{p.birthYear||"—"}</td><td>{p.birthPlace||"—"}</td><td>{p.relationships.length+p.relatedTo.length}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No people found.</div>}</div></>}
 {tab==="profile"&&current&&<><div className="heading"><div><h1>Person profile</h1><p className="muted">Live record from Neon PostgreSQL.</p></div><div className="actions"><button className="secondary" onClick={()=>setModal("edit")}>Edit</button><button className="danger" onClick={remove}>Delete</button></div></div><div className="card"><div className="detail"><div><div className="avatar">{initials(current)}</div></div><div><span className="badge">{current.gender==="M"?"Male":current.gender==="F"?"Female":"Family member"}</span><h2>{current.firstName} {current.lastName}</h2><p className="muted">{current.biography||"No biography added yet."}</p><div className="facts"><div className="fact"><b>Born</b>{current.birthYear||"Unknown"}</div><div className="fact"><b>Died</b>{current.deathYear||"Living / unknown"}</div><div className="fact"><b>Place</b>{current.birthPlace||"Unknown"}</div><div className="fact"><b>Parents</b>{parents.length?parents.map(p=>p.firstName).join(", "):"Not connected"}</div><div className="fact"><b>Spouse</b>{spouse?.firstName||"Not connected"}</div><div className="fact"><b>Children</b>{children.length}</div></div></div></div></div></>}
 </main></div>
 {modal&&<div className="modalback" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="modal"><div className="modalhead"><h2>{modal==="add"?"Add family member":modal==="edit"?"Edit person":"Connect people"}</h2><button className="close" onClick={()=>setModal(null)}>×</button></div>
 {modal==="relationship"?<form onSubmit={relation}><div className="formgrid"><div className="field"><label>Relationship</label><select name="type" defaultValue="PARENT"><option value="PARENT">Current person is parent</option><option value="CHILD">Current person is child</option><option value="SPOUSE">Spouse</option></select></div><div className="field"><label>Person</label><select name="person" required defaultValue=""><option value="" disabled>Select person</option>{people.filter(p=>p.id!==current?.id).map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName}</option>)}</select></div></div><div className="actions" style={{justifyContent:"flex-end",marginTop:20}}><button type="button" className="secondary" onClick={()=>setModal(null)}>Cancel</button><button className="primary">Save relationship</button></div></form>:<form onSubmit={modal==="add"?addPerson:editPerson}><div className="formgrid"><div className="field"><label>First name</label><input name="firstName" required defaultValue={modal==="edit"?current?.firstName:""}/></div><div className="field"><label>Last name</label><input name="lastName" required defaultValue={modal==="edit"?current?.lastName:""}/></div><div className="field"><label>Gender</label><select name="gender" defaultValue={modal==="edit"?current?.gender||"":""}><option value="">Not specified</option><option value="M">Male</option><option value="F">Female</option></select></div><div className="field"><label>Birth year</label><input name="birthYear" type="number" defaultValue={modal==="edit"?current?.birthYear||"":""}/></div><div className="field"><label>Death year</label><input name="deathYear" type="number" defaultValue={modal==="edit"?current?.deathYear||"":""}/></div><div className="field"><label>Birth/place</label><input name="birthPlace" defaultValue={modal==="edit"?current?.birthPlace||"":""}/></div></div><div className="field" style={{marginTop:14}}><label>Notes / biography</label><textarea name="biography" defaultValue={modal==="edit"?current?.biography||"":""}/></div><div className="actions" style={{justifyContent:"flex-end",marginTop:20}}><button type="button" className="secondary" onClick={()=>setModal(null)}>Cancel</button><button className="primary">{modal==="add"?"Add person":"Save changes"}</button></div></form>}
 </div></div>}</div>
}
